spring:
  application:
    name: SCHOOLSERVICE
  datasource:
    username: postgres
    password: lol
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://structuremade.de:5431/structuremade
  jpa:
    show-sql: on
    properties:
      hibernate:
        default_schema: services
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka.structuremade.de/eureka/
server:
  port: 80
